### ISSUE TITLE
Quotation Marks not being tracked when using the American International Keyboard distribution

### ISSUE THREAD

**Issue by rubenmate** [OnlyLys/Leaper#12]
This one could be a bit weird so I'll try my best to explain.

When you have the International American Distribution (which has the quotation marks acting as a dead key so you can accentuate or insert space to use the actual quotation marks) the ' " won't be tracked and when you tab it will insert a tab.

Thanks for your time, hope I did an average job explaining myself.

**Comment by OnlyLys** [comment]
Hi! 

I'll look into this and get back to you ASAP!

**Comment by OnlyLys** [comment]
@rubenmate Hi, do you think you can elaborate more on this issue? I'm not very familiar with the International American Distribution.

Are you looking to have `'"` autoclosing pairs be tracked?  If so, you can just specify `'"` in the `leaper.detectedPairs` configuration.

**Comment by rubenmate** [comment]
Mmm, I'lll try.
With the International American layout the '" will be a dead key (so you can use it to insert accentuations or press the space to insert the '" symbols).

This mess with the tracking in some way so when you press the tab (to move the cursor where it should move) it will add a tabulation.

I have recorded this video so you can see the difference between layouts:

https://streamable.com/i1ptzu

**Comment by OnlyLys** [comment]
@rubenmate I think I understand the issue now. I should be able to come out with a fix for this.

**Comment by OnlyLys** [comment]
@rubenmate If you can, please try out the [beta of version 0.11](https://github.com/OnlyLys/Leaper/releases/tag/0.11.0-beta.1) and let me know if everything works fine.

**Comment by rubenmate** [comment]
Still not working for me, it's behaving as before. 

Just in case, extra checked to uninstall leaper, restart VSCode and install again Leaper v0.11.0-beta.1.

**Comment by OnlyLys** [comment]
@rubenmate I'm trying a new approach right now. Hope to get it done soon.

**Comment by OnlyLys** [comment]
@rubenmate Can you please try the [second beta of version 0.11.0](https://github.com/OnlyLys/Leaper/releases/tag/0.11.0-beta.2)?

**Comment by rubenmate** [comment]
It is now working, thanks for your time addressing this issue! 😄

**Comment by OnlyLys** [comment]
@rubenmate There is a slight issue with the decorations not being cleaned up. I'll update it shortly.

**Comment by OnlyLys** [comment]
@rubenmate I've fixed it. Please use [the third beta](https://github.com/OnlyLys/Leaper/releases/tag/0.11.0-beta.3). Apologies for the issues.
